
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 26 17:02:35 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 21;
  public static final int RUPAR = 23;
  public static final int NAMESPACE = 20;
  public static final int GREATER = 38;
  public static final int LPAREN = 15;
  public static final int SEMI = 12;
  public static final int CONTINUE = 33;
  public static final int LESS = 39;
  public static final int FOR = 28;
  public static final int MINUS = 29;
  public static final int STATIC = 25;
  public static final int RPAREN = 10;
  public static final int AND = 40;
  public static final int OR = 41;
  public static final int COMMA = 17;
  public static final int CLASS = 22;
  public static final int DIV = 35;
  public static final int PLUS = 8;
  public static final int IF = 14;
  public static final int EXCL = 37;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int EQUAL = 11;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int MUL = 34;
  public static final int PERCENT = 36;
  public static final int NUMBER = 3;
  public static final int BREAK = 30;
  public static final int IDENT = 2;
  public static final int VOID = 19;
  public static final int COLON = 42;
  public static final int LBRACE = 16;
  public static final int ELSE = 7;
  public static final int POINT = 26;
  public static final int READ = 31;
  public static final int LUPAR = 24;
  public static final int CHARCONST = 5;
  public static final int RBRACE = 9;
  public static final int EXTENDS = 32;
  public static final int PROG = 6;
  public static final int TRUEFALSE = 4;
  public static final int PRINT = 18;
}

